/* Tables */
CREATE TABLE LABORATORIO (
    CodiceAlfaNum INTEGER NOT NULL,
    Nome INTEGER NOT NULL,
    NumPersonalComputer INTEGER NOT NULL,
    TipoImpiantoAudio INTEGER NOT NULL,
    PRIMARY KEY (CodiceAlfaNum)
);
CREATE TABLE AULA (
    CodiceAlfaNum INTEGER NOT NULL,
    CapienzaMassima INTEGER NOT NULL,
    Piano INTEGER NOT NULL,
    NumLavagna INTEGER NOT NULL,
    PRIMARY KEY (CodiceAlfaNum)
);
CREATE TABLE ESPERTO (
    CodiceFiscale INTEGER NOT NULL,
    Nome INTEGER NOT NULL,
    Cognome INTEGER NOT NULL,
    email INTEGER NOT NULL,
    Telefono INTEGER NOT NULL,
    PRIMARY KEY (CodiceFiscale)
);
CREATE TABLE ESAME (
    Codice INTEGER NOT NULL,
    Certificato INTEGER NOT NULL,
    Ente INTEGER NOT NULL,
    PRIMARY KEY (Codice)
);
CREATE TABLE TITOLO (
    Titolo INTEGER NOT NULL,
    PRIMARY KEY (Titolo)
);
CREATE TABLE TEMPO (
    DataInizio INTEGER NOT NULL,
    PRIMARY KEY (DataInizio)
);
CREATE TABLE PERSONA (
    Matricola INTEGER NOT NULL,
    Indirizzo INTEGER NOT NULL,
    Nome INTEGER NOT NULL,
    Telefono INTEGER NOT NULL,
    email INTEGER NOT NULL,
    PRIMARY KEY (Matricola)
);
CREATE TABLE CORSO (
    DataInizio INTEGER NOT NULL,
    Codice INTEGER NOT NULL,
    Costo INTEGER NOT NULL,
    Lingua INTEGER NOT NULL,
    Livelo INTEGER NOT NULL,
    PRIMARY KEY (DataInizio, Codice)
);
CREATE TABLE LEZIONE (
    CORSO_DataInizio INTEGER NOT NULL,
    CORSO_Codice INTEGER NOT NULL,
    Codice INTEGER NOT NULL,
    MassimoPartecipanti INTEGER NOT NULL,
    MinimoPartecipanti INTEGER NOT NULL,
    Data INTEGER NOT NULL,
    OraFine INTEGER NOT NULL,
    OraInizio INTEGER NOT NULL,
    LABORATORIO_CodiceAlfaNum INTEGER,
    AULA_CodiceAlfaNum INTEGER,
    PRIMARY KEY (CORSO_DataInizio, CORSO_Codice, Codice),
    FOREIGN KEY (CORSO_DataInizio) REFERENCES CORSO(DataInizio),
    FOREIGN KEY (CORSO_Codice) REFERENCES CORSO(Codice),
    FOREIGN KEY (LABORATORIO_CodiceAlfaNum) REFERENCES LABORATORIO(CodiceAlfaNum),
    FOREIGN KEY (AULA_CodiceAlfaNum) REFERENCES AULA(CodiceAlfaNum)
);
CREATE TABLE ISCRIZIONE (
    PERSONA_Matricola INTEGER NOT NULL,
    Data INTEGER NOT NULL,
    ESAME_Codice INTEGER NOT NULL,
    PRIMARY KEY (PERSONA_Matricola, Data),
    FOREIGN KEY (PERSONA_Matricola) REFERENCES PERSONA(Matricola),
    FOREIGN KEY (ESAME_Codice) REFERENCES ESAME(Codice)
);
CREATE TABLE HAS_ESPERTO (
    ESPERTO_CodiceFiscale INTEGER NOT NULL,
    CORSO_DataInizio INTEGER NOT NULL,
    CORSO_Codice INTEGER NOT NULL,
    PRIMARY KEY (ESPERTO_CodiceFiscale, CORSO_DataInizio, CORSO_Codice),
    FOREIGN KEY (ESPERTO_CodiceFiscale) REFERENCES ESPERTO(CodiceFiscale),
    FOREIGN KEY (CORSO_DataInizio) REFERENCES CORSO(DataInizio),
    FOREIGN KEY (CORSO_Codice) REFERENCES CORSO(Codice)
);
CREATE TABLE ISCRITTO (
    PERSONA_Matricola INTEGER NOT NULL,
    CORSO_DataInizio INTEGER NOT NULL,
    CORSO_Codice INTEGER NOT NULL,
    PRIMARY KEY (PERSONA_Matricola, CORSO_DataInizio, CORSO_Codice),
    FOREIGN KEY (PERSONA_Matricola) REFERENCES PERSONA(Matricola),
    FOREIGN KEY (CORSO_DataInizio) REFERENCES CORSO(DataInizio),
    FOREIGN KEY (CORSO_Codice) REFERENCES CORSO(Codice)
);
CREATE TABLE CONSEGUE (
    ESPERTO_CodiceFiscale INTEGER NOT NULL,
    TITOLO_Titolo INTEGER NOT NULL,
    DataConseguimento INTEGER NOT NULL,
    Voto INTEGER NOT NULL,
    Istituto INTEGER NOT NULL,
    PRIMARY KEY (ESPERTO_CodiceFiscale, TITOLO_Titolo),
    FOREIGN KEY (ESPERTO_CodiceFiscale) REFERENCES ESPERTO(CodiceFiscale),
    FOREIGN KEY (TITOLO_Titolo) REFERENCES TITOLO(Titolo)
);
CREATE TABLE RESPONSABILE (
    LABORATORIO_CodiceAlfaNum INTEGER NOT NULL,
    ESPERTO_CodiceFiscale INTEGER NOT NULL,
    TEMPO_DataInizio INTEGER NOT NULL,
    DataFine INTEGER,
    PRIMARY KEY (LABORATORIO_CodiceAlfaNum, ESPERTO_CodiceFiscale, TEMPO_DataInizio),
    FOREIGN KEY (LABORATORIO_CodiceAlfaNum) REFERENCES LABORATORIO(CodiceAlfaNum),
    FOREIGN KEY (ESPERTO_CodiceFiscale) REFERENCES ESPERTO(CodiceFiscale),
    FOREIGN KEY (TEMPO_DataInizio) REFERENCES TEMPO(DataInizio)
);
CREATE TABLE FREQUENZA (
    PERSONA_Matricola INTEGER NOT NULL,
    LEZIONE_CORSO_DataInizio INTEGER NOT NULL,
    LEZIONE_CORSO_Codice INTEGER NOT NULL,
    LEZIONE_Codice INTEGER NOT NULL,
    PRIMARY KEY (PERSONA_Matricola, LEZIONE_CORSO_DataInizio, LEZIONE_CORSO_Codice, LEZIONE_Codice),
    FOREIGN KEY (PERSONA_Matricola) REFERENCES PERSONA(Matricola),
    FOREIGN KEY (LEZIONE_CORSO_DataInizio) REFERENCES LEZIONE(CORSO_DataInizio),
    FOREIGN KEY (LEZIONE_CORSO_Codice) REFERENCES LEZIONE(CORSO_Codice),
    FOREIGN KEY (LEZIONE_Codice) REFERENCES LEZIONE(Codice)
);