/* Tables */
CREATE TABLE TRIBUNALE (
    Codice INTEGER NOT NULL,
    Civico_Indirizzo INTEGER NOT NULL,
    Via_Indirizzo INTEGER NOT NULL,
    Citta_Indirizzo INTEGER NOT NULL,
    PRIMARY KEY (Codice)
);
CREATE TABLE TEMPO (
    GiornoSettimana INTEGER NOT NULL,
    PRIMARY KEY (GiornoSettimana)
);
CREATE TABLE CAUSA (
    Codice INTEGER NOT NULL,
    Nome INTEGER NOT NULL,
    DataInizio INTEGER NOT NULL,
    DataFine INTEGER,
    AVVOCATO_Codice INTEGER NOT NULL,
    PRIMARY KEY (Codice),
    FOREIGN KEY (AVVOCATO_Codice) REFERENCES AVVOCATO(Codice)
);
CREATE TABLE GIUDICE (
    Codice INTEGER NOT NULL,
    Nome INTEGER NOT NULL,
    Cellulare INTEGER NOT NULL,
    PRIMARY KEY (Codice)
);
CREATE TABLE TITOLO (
    Titolo INTEGER NOT NULL,
    PRIMARY KEY (Titolo)
);
CREATE TABLE AVVOCATO (
    Codice INTEGER NOT NULL,
    IndirizzoLavoro INTEGER NOT NULL,
    Nome INTEGER NOT NULL,
    Cellulare INTEGER NOT NULL,
    PRIMARY KEY (Codice)
);
CREATE TABLE TELEFONO (
    Telefono INTEGER NOT NULL,
    TRIBUNALE_Codice INTEGER NOT NULL,
    PRIMARY KEY (Telefono),
    FOREIGN KEY (TRIBUNALE_Codice) REFERENCES TRIBUNALE(Codice)
);
CREATE TABLE AULA (
    TRIBUNALE_Codice INTEGER NOT NULL,
    Codice INTEGER NOT NULL,
    Nome INTEGER NOT NULL,
    PRIMARY KEY (TRIBUNALE_Codice, Codice),
    FOREIGN KEY (TRIBUNALE_Codice) REFERENCES TRIBUNALE(Codice)
);
CREATE TABLE UDIENZA (
    AULA_TRIBUNALE_Codice INTEGER NOT NULL,
    AULA_Codice INTEGER NOT NULL,
    Data INTEGER NOT NULL,
    OraInizio INTEGER NOT NULL,
    OraFIne INTEGER NOT NULL,
    CAUSA_Codice INTEGER NOT NULL,
    PRIMARY KEY (AULA_TRIBUNALE_Codice, AULA_Codice, Data, OraInizio),
    FOREIGN KEY (AULA_TRIBUNALE_Codice) REFERENCES AULA(TRIBUNALE_Codice),
    FOREIGN KEY (AULA_Codice) REFERENCES AULA(Codice),
    FOREIGN KEY (CAUSA_Codice) REFERENCES CAUSA(Codice)
);
CREATE TABLE APERTURA (
    TRIBUNALE_Codice INTEGER NOT NULL,
    TEMPO_GiornoSettimana INTEGER NOT NULL,
    OraInizio INTEGER NOT NULL,
    OraFine INTEGER NOT NULL,
    PRIMARY KEY (TRIBUNALE_Codice, TEMPO_GiornoSettimana),
    FOREIGN KEY (TRIBUNALE_Codice) REFERENCES TRIBUNALE(Codice),
    FOREIGN KEY (TEMPO_GiornoSettimana) REFERENCES TEMPO(GiornoSettimana)
);
CREATE TABLE HAS_TITOLO (
    GIUDICE_Codice INTEGER NOT NULL,
    TITOLO_Titolo INTEGER NOT NULL,
    DataAssegnato INTEGER NOT NULL,
    Motivazione INTEGER NOT NULL,
    PRIMARY KEY (GIUDICE_Codice, TITOLO_Titolo),
    FOREIGN KEY (GIUDICE_Codice) REFERENCES GIUDICE(Codice),
    FOREIGN KEY (TITOLO_Titolo) REFERENCES TITOLO(Titolo)
);