/* Tables */
CREATE TABLE PISCINA (
    Nome INTEGER NOT NULL,
    Telefono INTEGER NOT NULL,
    Responsabile INTEGER NOT NULL,
    MeseInizio INTEGER,
    MeseFine INTEGER,
    Type INTEGER NOT NULL,
    NumeroCivico_Indirizzo INTEGER NOT NULL,
    Via_Indirizzo INTEGER NOT NULL,
    Citta_Indirizzo INTEGER NOT NULL,
    TipoVia_Indirizzo INTEGER NOT NULL,
    PRIMARY KEY (Nome)
);
CREATE TABLE INGRESSO_SINGOLO (
    CodiceFiscale INTEGER NOT NULL,
    Nome INTEGER NOT NULL,
    Telefono INTEGER NOT NULL,
    Citta_Indirizzo INTEGER NOT NULL,
    NumeroCivico_Indirizzo INTEGER NOT NULL,
    Via_Indirizzo INTEGER NOT NULL,
    TipoVia_Indirizzo INTEGER NOT NULL,
    PISCINA_Nome INTEGER NOT NULL,
    Data INTEGER NOT NULL,
    PRIMARY KEY (CodiceFiscale),
    FOREIGN KEY (PISCINA_Nome) REFERENCES PISCINA(Nome)
);
CREATE TABLE ISCRITTO (
    CodiceFiscale INTEGER NOT NULL,
    DataCertificato INTEGER NOT NULL,
    Medico INTEGER NOT NULL,
    DataNascita INTEGER NOT NULL,
    Nome INTEGER NOT NULL,
    Telefono INTEGER NOT NULL,
    Citta_Indirizzo INTEGER NOT NULL,
    NumeroCivico_Indirizzo INTEGER NOT NULL,
    Via_Indirizzo INTEGER NOT NULL,
    TipoVia_Indirizzo INTEGER NOT NULL,
    PRIMARY KEY (CodiceFiscale)
);
CREATE TABLE TEMPO2 (
    DataInizio INTEGER NOT NULL,
    PRIMARY KEY (DataInizio)
);
CREATE TABLE INSEGNANTE (
    CodiceFiscale INTEGER NOT NULL,
    Cellulare INTEGER,
    Nome INTEGER NOT NULL,
    PRIMARY KEY (CodiceFiscale)
);
CREATE TABLE TEMPO (
    Giorno INTEGER NOT NULL,
    PRIMARY KEY (Giorno)
);
CREATE TABLE CORSO (
    PISCINA_Nome INTEGER NOT NULL,
    Nome INTEGER NOT NULL,
    Costo INTEGER NOT NULL,
    MinPartecipanti INTEGER NOT NULL,
    MaxPartecipanti INTEGER NOT NULL,
    PRIMARY KEY (PISCINA_Nome, Nome),
    FOREIGN KEY (PISCINA_Nome) REFERENCES PISCINA(Nome)
);
CREATE TABLE LEZIONE (
    TEMPO_Giorno INTEGER NOT NULL,
    CORSO_PISCINA_Nome INTEGER NOT NULL,
    CORSO_Nome INTEGER NOT NULL,
    OraFine INTEGER NOT NULL,
    OraInizio INTEGER NOT NULL,
    PRIMARY KEY (TEMPO_Giorno, CORSO_PISCINA_Nome, CORSO_Nome),
    FOREIGN KEY (TEMPO_Giorno) REFERENCES TEMPO(Giorno),
    FOREIGN KEY (CORSO_PISCINA_Nome) REFERENCES CORSO(PISCINA_Nome),
    FOREIGN KEY (CORSO_Nome) REFERENCES CORSO(Nome)
);
CREATE TABLE ISCRIZIONE (
    ISCRITTO_CodiceFiscale INTEGER NOT NULL,
    CORSO_PISCINA_Nome INTEGER NOT NULL,
    CORSO_Nome INTEGER NOT NULL,
    PRIMARY KEY (ISCRITTO_CodiceFiscale, CORSO_PISCINA_Nome, CORSO_Nome),
    FOREIGN KEY (ISCRITTO_CodiceFiscale) REFERENCES ISCRITTO(CodiceFiscale),
    FOREIGN KEY (CORSO_PISCINA_Nome) REFERENCES CORSO(PISCINA_Nome),
    FOREIGN KEY (CORSO_Nome) REFERENCES CORSO(Nome)
);
CREATE TABLE HAS_QUALIFICA (
    INSEGNANTE_CodiceFiscale INTEGER NOT NULL,
    QUALIFICA_Qualifica INTEGER NOT NULL,
    PRIMARY KEY (INSEGNANTE_CodiceFiscale, QUALIFICA_Qualifica),
    FOREIGN KEY (INSEGNANTE_CodiceFiscale) REFERENCES INSEGNANTE(CodiceFiscale)
);
CREATE TABLE LAVORA (
    PISCINA_Nome INTEGER NOT NULL,
    TEMPO2_DataInizio INTEGER NOT NULL,
    INSEGNANTE_CodiceFiscale INTEGER NOT NULL,
    DataFine INTEGER,
    PRIMARY KEY (PISCINA_Nome, TEMPO2_DataInizio, INSEGNANTE_CodiceFiscale),
    FOREIGN KEY (PISCINA_Nome) REFERENCES PISCINA(Nome),
    FOREIGN KEY (TEMPO2_DataInizio) REFERENCES TEMPO2(DataInizio),
    FOREIGN KEY (INSEGNANTE_CodiceFiscale) REFERENCES INSEGNANTE(CodiceFiscale)
);