// <auto-generated />
using System;
using BibliotecaWebService.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace _20241015_BibliotecaWebService_ASP.NET_CoreWebAPI.Migrations
{
    [DbContext(typeof(GestioneBibliotecaContext))]
    partial class GestioneBibliotecaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_20241015_BibliotecaWebService_ASP.NET_CoreWebAPI.Models.Entities.ClienteEntity", b =>
                {
                    b.Property<string>("CodiceFiscale")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CodiceFiscale");

                    b.ToTable("Clienti");
                });

            modelBuilder.Entity("_20241015_BibliotecaWebService_ASP.NET_CoreWebAPI.Models.Entities.LibroEntity", b =>
                {
                    b.Property<string>("ISBN")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Autori")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("ISBN");

                    b.ToTable("Libri");
                });

            modelBuilder.Entity("_20241015_BibliotecaWebService_ASP.NET_CoreWebAPI.Models.Entities.PrestitoEntity", b =>
                {
                    b.Property<string>("CodiceFiscale")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ISBN")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DataInizio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFine")
                        .HasColumnType("datetime2");

                    b.HasKey("CodiceFiscale", "ISBN", "DataInizio");

                    b.HasIndex("ISBN");

                    b.ToTable("Prestiti");
                });

            modelBuilder.Entity("_20241015_BibliotecaWebService_ASP.NET_CoreWebAPI.Models.Entities.PrestitoEntity", b =>
                {
                    b.HasOne("_20241015_BibliotecaWebService_ASP.NET_CoreWebAPI.Models.Entities.ClienteEntity", "Cliente")
                        .WithMany("Prestiti")
                        .HasForeignKey("CodiceFiscale")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_20241015_BibliotecaWebService_ASP.NET_CoreWebAPI.Models.Entities.LibroEntity", "Libro")
                        .WithMany("Prestiti")
                        .HasForeignKey("ISBN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Libro");
                });

            modelBuilder.Entity("_20241015_BibliotecaWebService_ASP.NET_CoreWebAPI.Models.Entities.ClienteEntity", b =>
                {
                    b.Navigation("Prestiti");
                });

            modelBuilder.Entity("_20241015_BibliotecaWebService_ASP.NET_CoreWebAPI.Models.Entities.LibroEntity", b =>
                {
                    b.Navigation("Prestiti");
                });
#pragma warning restore 612, 618
        }
    }
}
