frase = '    Adolpho Silverio Figueiredo Neto   '
print(frase)
print(frase.replace('Neto','Junior'))
print(frase.upper().count('o'))
print(frase.upper().count('o'))
print(frase.upper())
print(frase.lower().count('o'))
print(frase.lower())
print(frase.capitalize())
print(frase.title())
print(frase.strip())
print(frase.rstrip())
print(frase.lstrip())