
services:
  flask_app:
    build: .  # Costruisce l'immagine dal Dockerfile
    container_name: flask_app
    restart: always
    ports:
      - "5000:5000"  # Esponi la porta Flask
    env_file:
      - .env  # Specifica il file .env
    environment:
      - PYTHONUNBUFFERED=1

