// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _20241024_GestioneMagazzino.Models;

#nullable disable

namespace _20241024_GestioneMagazzino.Migrations
{
    [DbContext(typeof(GestioneMagazzinoContext))]
    [Migration("20241026084150_Version_0.02")]
    partial class Version_002
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_20241024_GestioneMagazzino.Models.Entities.ClienteEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Clienti");
                });

            modelBuilder.Entity("_20241024_GestioneMagazzino.Models.Entities.FornitoreEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Fornitori");
                });

            modelBuilder.Entity("_20241024_GestioneMagazzino.Models.Entities.MovimentoMagazzinoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdOrdineClienteDettaglio")
                        .HasColumnType("int");

                    b.Property<int>("IdOrdineFornitoreDettaglio")
                        .HasColumnType("int");

                    b.Property<int>("IdProdotto")
                        .HasColumnType("int");

                    b.Property<int?>("ProdottoEntityId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantita")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdOrdineClienteDettaglio");

                    b.HasIndex("IdOrdineFornitoreDettaglio");

                    b.HasIndex("IdProdotto");

                    b.HasIndex("ProdottoEntityId");

                    b.ToTable("Movimenti");
                });

            modelBuilder.Entity("_20241024_GestioneMagazzino.Models.Entities.OrdineClienteDettaglioEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdOrdineClienteTesta")
                        .HasColumnType("int");

                    b.Property<int>("IdProdotto")
                        .HasColumnType("int");

                    b.Property<int?>("ProdottoEntityId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantita")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdOrdineClienteTesta");

                    b.HasIndex("IdProdotto");

                    b.HasIndex("ProdottoEntityId");

                    b.ToTable("OrdineClienteDettagli");
                });

            modelBuilder.Entity("_20241024_GestioneMagazzino.Models.Entities.OrdineClienteTestaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.ToTable("OrdineClienteTeste");
                });

            modelBuilder.Entity("_20241024_GestioneMagazzino.Models.Entities.OrdineFornitoreDettaglioEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdOrdineFornitoreTesta")
                        .HasColumnType("int");

                    b.Property<int>("IdProdotto")
                        .HasColumnType("int");

                    b.Property<int?>("ProdottoEntityId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantita")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdOrdineFornitoreTesta");

                    b.HasIndex("IdProdotto");

                    b.HasIndex("ProdottoEntityId");

                    b.ToTable("OrdineFornitoreDettagli");
                });

            modelBuilder.Entity("_20241024_GestioneMagazzino.Models.Entities.OrdineFornitoreTestaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<int>("IdFornitore")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdFornitore");

                    b.ToTable("OrdineFornitoreTeste");
                });

            modelBuilder.Entity("_20241024_GestioneMagazzino.Models.Entities.ProdottoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Altezza")
                        .HasColumnType("int");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Larghezza")
                        .HasColumnType("int");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.Property<int>("Profondita")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Prodotti");
                });

            modelBuilder.Entity("_20241024_GestioneMagazzino.Models.Entities.MovimentoMagazzinoEntity", b =>
                {
                    b.HasOne("_20241024_GestioneMagazzino.Models.Entities.OrdineClienteDettaglioEntity", "OrdineClienteDettaglio")
                        .WithMany()
                        .HasForeignKey("IdOrdineClienteDettaglio")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("_20241024_GestioneMagazzino.Models.Entities.OrdineFornitoreDettaglioEntity", "OrdineFornitoreDettaglio")
                        .WithMany()
                        .HasForeignKey("IdOrdineFornitoreDettaglio")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("_20241024_GestioneMagazzino.Models.Entities.ProdottoEntity", "Prodotto")
                        .WithMany()
                        .HasForeignKey("IdProdotto")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("_20241024_GestioneMagazzino.Models.Entities.ProdottoEntity", null)
                        .WithMany("MovimentiMagazzino")
                        .HasForeignKey("ProdottoEntityId");

                    b.Navigation("OrdineClienteDettaglio");

                    b.Navigation("OrdineFornitoreDettaglio");

                    b.Navigation("Prodotto");
                });

            modelBuilder.Entity("_20241024_GestioneMagazzino.Models.Entities.OrdineClienteDettaglioEntity", b =>
                {
                    b.HasOne("_20241024_GestioneMagazzino.Models.Entities.OrdineClienteTestaEntity", "OrdineClienteTesta")
                        .WithMany("Dettagli")
                        .HasForeignKey("IdOrdineClienteTesta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_20241024_GestioneMagazzino.Models.Entities.ProdottoEntity", "Prodotto")
                        .WithMany()
                        .HasForeignKey("IdProdotto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_20241024_GestioneMagazzino.Models.Entities.ProdottoEntity", null)
                        .WithMany("OrdineClienteDettagli")
                        .HasForeignKey("ProdottoEntityId");

                    b.Navigation("OrdineClienteTesta");

                    b.Navigation("Prodotto");
                });

            modelBuilder.Entity("_20241024_GestioneMagazzino.Models.Entities.OrdineClienteTestaEntity", b =>
                {
                    b.HasOne("_20241024_GestioneMagazzino.Models.Entities.ClienteEntity", "Cliente")
                        .WithMany("Ordini")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("_20241024_GestioneMagazzino.Models.Entities.OrdineFornitoreDettaglioEntity", b =>
                {
                    b.HasOne("_20241024_GestioneMagazzino.Models.Entities.OrdineFornitoreTestaEntity", "OrdineFornitoreTesta")
                        .WithMany("Dettagli")
                        .HasForeignKey("IdOrdineFornitoreTesta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_20241024_GestioneMagazzino.Models.Entities.ProdottoEntity", "Prodotto")
                        .WithMany()
                        .HasForeignKey("IdProdotto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_20241024_GestioneMagazzino.Models.Entities.ProdottoEntity", null)
                        .WithMany("OrdineFornitoreDettagli")
                        .HasForeignKey("ProdottoEntityId");

                    b.Navigation("OrdineFornitoreTesta");

                    b.Navigation("Prodotto");
                });

            modelBuilder.Entity("_20241024_GestioneMagazzino.Models.Entities.OrdineFornitoreTestaEntity", b =>
                {
                    b.HasOne("_20241024_GestioneMagazzino.Models.Entities.FornitoreEntity", "Fornitore")
                        .WithMany("Ordini")
                        .HasForeignKey("IdFornitore")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fornitore");
                });

            modelBuilder.Entity("_20241024_GestioneMagazzino.Models.Entities.ClienteEntity", b =>
                {
                    b.Navigation("Ordini");
                });

            modelBuilder.Entity("_20241024_GestioneMagazzino.Models.Entities.FornitoreEntity", b =>
                {
                    b.Navigation("Ordini");
                });

            modelBuilder.Entity("_20241024_GestioneMagazzino.Models.Entities.OrdineClienteTestaEntity", b =>
                {
                    b.Navigation("Dettagli");
                });

            modelBuilder.Entity("_20241024_GestioneMagazzino.Models.Entities.OrdineFornitoreTestaEntity", b =>
                {
                    b.Navigation("Dettagli");
                });

            modelBuilder.Entity("_20241024_GestioneMagazzino.Models.Entities.ProdottoEntity", b =>
                {
                    b.Navigation("MovimentiMagazzino");

                    b.Navigation("OrdineClienteDettagli");

                    b.Navigation("OrdineFornitoreDettagli");
                });
#pragma warning restore 612, 618
        }
    }
}
