a = input('Enter the value to be searched: ')
print('The primitive type of this value is', type(a))
print('Does the value "{}" contain only spaces? '.format(a), a.isspace())
print('Is the value "{}" a number? '.format(a), a.isnumeric())
print('Is the value "{}" a letter? '.format(a), a.isalpha())
print('Is the value "{}" alphanumeric? '.format(a), a.isalnum())
print('Is the value "{}" uppercase? '.format(a), a.isupper())
print('Is the value "{}" lowercase? '.format(a), a.islower())
print('Is the value "{}" capitalized? '.format(a), a.istitle())
