print("---------------------------------------")
lista1 = list()
print(lista1)
lista2 = list("stringa")
print(lista2)
print("---------------------------------------")
lista = [1, 2, 3, 4]
lista.append(10)
print(lista)
lista.extend([30,40])
print(lista)
lista.insert(2,-1)
print(lista)
print("---------------------------------------")
lista = [1, 2, 3, 4]
print(lista.pop())
print(lista)
lista.remove(2)
print(lista)
lista.clear()
print(lista)
print("---------------------------------------")
lista = [10, -2, 3, 1]
print(lista)
lista.sort()
print(lista)
lista.reverse()
print(lista)
print("---------------------------------------")
lista = [1, 2, 3, 4]
for ele in reversed(lista):
    print(ele,end=" ")
print("\n",lista)
print("\n---------------------------------------")
